### PR TITLE
Update feed link and photo of Gaurav Dhingra

### PR DESCRIPTION
**Pull request by gxyd**

### CODE REVIEW

**Comment by gxyd** [comment]
l should reduce the size of pic.

**Comment by gxyd** [comment]
Done, I have updated the photo. It is ready from my side.

**Comment by gxyd** [comment]
Thanks @certik . Will it take sometime for the feed blogs to appear on the planet sympy website?

**Comment by certik** [comment]
@gxyd yes, see the README for details of how exactly it gets updated. You can watch the update on gitlab (see README for a link).

**Pull request merged**
