### PR TITLE
"Microblogging" -> "Twitter"

### PR DESCRIPTION
**Pull request by asmeurer**
Nobody uses the word "microblogging" anymore.

### CODE REVIEW

**Comment by asmeurer** [comment]
How long does it take to go live? Is it a manual process or automatic?

**Comment by certik** [comment]
Currently I have to do it manually.

**Comment by certik** [comment]
@asmeurer, I created the issue #24 for automatic deployment. Any help setting this up is welcome.

**Comment by certik** [comment]
@asmeurer , now when #25 is in, you can check the git revision (of this repository) that is being deployed at: https://github.com/planet-sympy/planet.sympy.org/blob/gh-pages/git_revision

We should also expose it on the webpage itself, I created an issue #26 for that.

**Pull request merged**
