### PR TITLE
Fix all warnings and errors

### PR DESCRIPTION
**Pull request by certik**
This fixes all warnings and errors from:

https://gitlab.com/certik/planet-sympy-updater/-/jobs/79705574

### CODE REVIEW

**Comment by asmeurer** [comment]
So if a single URL is wrong it stops the site from building?

**Comment by certik** [comment]
No, it just gives warnings. The website keeps building. The reason it didn't build was because GitLab upgraded their API from v3 to v4, and my cronjob was still using v3. I just upgraded to v4 and now everything works again.

**Comment by asmeurer** [comment]
I see. Is there any way we can get notifications of failures? Would it help to move the repo to https://gitlab.com/sympy (which I think we should do anyway)?

**Comment by certik** [comment]
If you move to GitHub, then you can't use GitLab-CI. So we would have to use Travis or Circle-CI. Do any of them allow to rebuild every 20 minutes based on a simple webhook, as I do with GitLab-CI?

**Comment by asmeurer** [comment]
Actually do you have access to the GitLab `sympy` group? I thought that I had created it, but it seems I don't have access.

**Comment by asmeurer** [comment]
Not move to GitHub, move the sympy projects from your username on GitLab to the `sympy` group on GitLab. [It seems you did create it](https://gitlab.com/groups/sympy/-/group_members). Can you give me access

**Comment by certik** [comment]
Sure, you have access now and I moved it: https://gitlab.com/sympy/planet-sympy-updater

**Comment by asmeurer** [comment]
Great thanks. I don't know if that will notify me when the builds fail, but at least I will now have the ability to fix things if I need to.

**Pull request merged**
