### PR TITLE
Blog link and photo update

### PR DESCRIPTION
**Pull request by Shekharrajak**
I shifted the blog in [github](http://shekharrajak.github.io/) using Jekyll. Now feed.xml is working fine.

### CODE REVIEW

**Comment by Shekharrajak** [comment]
Previous static blog was [this](http://s-hacker.info/blog/gsoc16/subcat.html).

**Comment by Shekharrajak** [comment]
@Sumith1896 , my blog is not coming in http://planet.sympy.org/. It is still showing the previous feed link. Please check issue. Thanks.

**Comment by Sumith1896** [comment]
Will have a look tonight.

**Comment by Sumith1896** [comment]
@Shekharrajak I'm afraid the RSS has not been setup correctly in your blog, can you have a look?

For example when you open the feed link http://shekharrajak.github.io/feed.xml you should be able to see the actual content inside the blog post. Do you have a look at feeds of other blogs in planet, for example http://srajangarg.github.io/feed.xml ? If it's a custom made theme, try to get the feed right, then it will update to the planet. Do let me know if you have further queries.

**Comment by Shekharrajak** [comment]
Thanks @Sumith1896 I have edited the feed.xml same as http://srajangarg.github.io/feed.xml . Hope we will see in next fetch.

**Comment by certik** [comment]
I also just deployed the latest image on the server, so it should have this PR in it now.

**Comment by Shekharrajak** [comment]
Thanks @certik

**Pull request merged**
