### PR TITLE
Added open graph meta tags

### PR DESCRIPTION
**Pull request by ranveeraggarwal**
[OG tags](https://developers.facebook.com/docs/sharing/webmasters#markup) allow you to control how content is shared on social media. Next time someone shares a link to Planet SymPy, it'll have the logo and the description, instead of whatever the social networking website gathers. A way to test how a share will be rendered on Facebook is the [Facebook URL Debugger](https://developers.facebook.com/tools/debug/).

### CODE REVIEW

**Comment by Sumith1896** [comment]
Cool, +1 :)

**Comment by Sumith1896** [comment]
@certik Could you have a look too?

My `Merge PR` button is messed

**Comment by certik** [comment]
The PR is +1.

@Sumith1896 can you send a screenshot of your merge button?

**Comment by Sumith1896** [comment]
ss

[write access](https://help.github.com/articles/what-are-the-different-access-permissions/)

[authorized](https://help.github.com/articles/about-protected-branches/)

**Comment by certik** [comment]
@Sumith1896 I see. It looks like if you don't have permissions, but I just checked and you have write permissions. So I don't know what is going on.

**Comment by certik** [comment]
@Sumith1896 I see --- you had write access, but the master branch was restricted further. I just added the team you are in to be able to merge. So you should be able to merge now. Sorry about that.

**Pull request merged**
