### PR TITLE
Add name to the blog title

### PR DESCRIPTION
**Pull request by asmeurer**
Fixes https://github.com/sympy/planet-sympy/issues/36

I haven't been able to test this, so please make sure it works. I think an
alternate way to fix this would be to edit the rss script (in case you don't
want the name to appear this way on the planet page itself).

### CODE REVIEW

**Comment by asmeurer** [comment]
@certik please review.

**Comment by asmeurer** [comment]
Also, can you update the instructions on how to run this on the README. `docker build -t username/planet-sympy:v1 .` doesn't look right to me.

**Comment by certik** [comment]
@asmeurer I'll add instructions how to run a webserver inside docker, so that you can inspect the planet with your browser. Good point. (The command you quoted is right, but that only builds the image.)

**Comment by certik** [comment]
@asmeurer actually, it is already tested on Travis. Please push your branch into a local branch in sympy/planet-sympy. Then Travis will push the planet into this testing repository: https://github.com/planet-sympy/planet.sympy.org-test/tree/gh-pages, so you can inspect it that it works.

This is what I was working on lately.

**Comment by asmeurer** [comment]
OK, I pushed the branch to origin.

**Comment by asmeurer** [comment]
Looks like it works https://planet-sympy.github.io/planet.sympy.org-test/

screen shot 2016-05-10 at 12 18 02 pm

It also includes the username. I don't know if there is a way to only include the full name.

**Comment by asmeurer** [comment]
[This line](https://github.com/sympy/planet-sympy/pull/39/files#diff-a8d5b079a7f31828470ec56e821d47a5R18) suggests that the handle should be separate. But it isn't for some reason.

**Comment by asmeurer** [comment]
Actually scratch that. It looks like this doesn't affect the RSS https://planet-sympy.github.io/planet.sympy.org-test/rss10.xml. So I'll need to fix this PR.

**Comment by certik** [comment]
@asmeurer ok. Ping me once you want me to review. Once we merge into a master, it's easy for me to update our server, it's just this:
```
ssh our_server
cd some_dir
./deploy.sh
```
This downloads the latest docker image from docker hub (which is build automatically from the latest master by docker hub itself), and switches to it. It's quick and robust.

**Comment by asmeurer** [comment]
The RSS script is a bit harder to figure out. I'll probably need to figure out how to run the Docker container to test this. Or, probably easier, run the code locally.

I think [this](https://github.com/sympy/planet-sympy/blob/3d233e430573e383dd390fa375a7d7b649a3051f/planet/planetsympy/plugins/rss.py#L110-L114) is the relevant line, but I don't understand what it does. In particular, what is this `s` variable that sometimes overwrites the title.

**Comment by asmeurer** [comment]
OK, I believe I have this working for the RSS feed now.

**Comment by asmeurer** [comment]
OK, let me know when it is deployed. The goal is to get the author names to appear in the tweets from the [Twitter feed](https://twitter.com/planetsympy).

**Comment by certik** [comment]
@asmeurer you can see it yourself when it gets deployed here: https://gitlab.com/certik/planet-sympy-updater/pipelines, those jobs are triggered every 20 min.

To check that it got deployed, one has to check that the proper revision of the docker container got downloaded. We should make it easier by simply putting the git revision of this `planet-sympy` repository into the deployment. There were some issues with it, so my PR for that is still WIP:

https://github.com/sympy/planet-sympy/pull/33

**Comment by asmeurer** [comment]
I think it worked. I'll know for sure when someone posts something if the tweet is right.

**Pull request merged**
