### PR TITLE
Add bjodah

### PR DESCRIPTION
**Pull request by bjodah**
Adds my blog

### CODE REVIEW

**Comment by bjodah** [comment]
@certik absolutely (github has been having some server issues during the past hours)

**Comment by asmeurer** [comment]
@certik I forgot, can I just merge these, or do you have to deploy manually?

**Comment by asmeurer** [comment]
Travis sudo:required builds have been having issues https://www.traviscistatus.com/

**Comment by certik** [comment]
As described in the README, the deployment is automatic. @asmeurer I tried to further clarify this in #56. 

@bjodah, @asmeurer if you have ideas how to make the README even clearer, I would appreciate any PRs.

**Comment by asmeurer** [comment]
Thanks. I couldn't tell if the full deployment was automatic or just the updating of the feed.

**Comment by bjodah** [comment]
Looks like my non ASCII-compliant name is causing trouble here. Should I change to Bjoern or do you want to add support for e.g. utf-8?

**Comment by certik** [comment]
Support for utf8 would be great. I thought my name used to be there.

**Comment by bjodah** [comment]
So the choice of encoding in rawdog depends on system environment:
https://github.com/sympy/planet-sympy/blob/c83f2090fe8306e39171df2b1e19a7eaae670a85/planet/rawdoglib/rawdog.py#L1917

I feel it's not worthwhile fixing this right now for me (I'm fine with "Bjoern").

**Comment by certik** [comment]
Ok, I created #58 for the Unicode issue.

**Comment by certik** [comment]
#59 fixed the unicode stuff. @asmeurer just an example of why Docker is important --- the environment is under control, so this utf8 fix will work, while previously this might have worked on Travis, and then fail when it was actually deployed. With Docker, the fix works both on Travis as well as when it's deployed.

**Pull request merged**
